### Signin
POST http://localhost:3000/users/signin HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "user1@example.com",
    "password_hash": "P@$$w0rd"
}


### Signup
POST http://localhost:3000/users/signup HTTP/1.1
Content-Type: application/json

{
    "email": "user3@example.com",
    "password_hash": "P@$$w0rd",
    "full_name": "Example User 3"
}


### Get profile
GET http://localhost:3000/users/profile HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcxYTVlMDYwLTRlNDYtNDA3Mi1iNDIzLWQzMzE2ZGUyMWUyYiIsImlhdCI6MTcyODY0MTA2MX0.ps8oqOKHU1WXvq3MXNTp6cgmkik2Jf7jpL9JArbCRkk


