apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-db
  namespace: gatekeeper
spec:
  replicas: 1 # Adjust based on your needs
  selector:
    matchLabels:
      app: pgsql-db
  template:
    metadata:
      labels:
        app: pgsql-db
    spec:
      containers:
        - name: pgsql
          image: postgres:latest # Standard PostgreSQL image from Docker Hub
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: gatekeeper-config
                  key: db-name
