apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-api
  namespace: gatekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatekeeper-api
  template:
    metadata:
      labels:
        app: gatekeeper-api
    spec:
      containers:
        - name: gatekeeper
          image: arm1997/gatekeeper:dev
          ports:
            - containerPort: 3000
              
          env:
            - name: DB_HOST
              value: "pgsql" # kubernetes service name will be resolved by K8
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: gatekeeper-config
                  key: db-port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: gatekeeper-config
                  key: db-name
