apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-api-service
  namespace: gatekeeper
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: gatekeeper-api
