POST {{baseUrl}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "name": "User Name 2",
    "email": "user2@example.com",
    "password": "@@Bykea123"
}


### Login
POST {{baseUrl}}/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "user1@example.com",   
    "password": "@@Bykea123"
}

### Validate
GET {{baseUrl}}/auth/validate HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU3ZTQxOTE1LTRiOWItNGViNC05YjFiLWQ2ZjNiZWQ0ZTBhYiIsImlhdCI6MTcyOTY5Mjc2Mn0.UZJVO8-BzHjWe90m1ytOK4G_0CGrj5PRizEHgszDcXw